apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app-blue
  template:
    metadata:
      labels:
        app: messaging-app-blue
    spec:
      containers:
      - name: messaging-app-blue
        image: your-docker-image:latest:2.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app-blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP